
	
	{m=document.getElementById(f.slidenavid);var a=document.createElement("span");f.animate&&(f.startAnimated?a.innerHTML='<button data-stop=true id="slideshowbutton">'+f.stoptext+"</button>":a.innerHTML='<button data-start=true id="slideshowbutton">'+f.starttext+"</button>",m.appendChild(a)),m.addEventListener("click",function(e){console.log("button click for slide show");var t=e.target;"button"===t.localName&&(t.getAttribute("data-stop")?s():t.getAttribute("data-start")&&o())},!0),d.className="active carousel with-slidenav"}u[0].parentNode.addEventListener("transitionend",function(n){var i=n.target;e(i,"in-transition"),t(i,"current")&&(v&&(i.setAttribute("tabindex","-1"),i.focus(),v=!1),g&&(i.removeAttribute("aria-live"),g=!1))}),d.addEventListener("focusin",function(e){t(e.target,"slide")||l()}),d.addEventListener("focusout",function(e){t(e.target,"slide")||o()}),i(c=0),f.startAnimated&&(p=setTimeout(r,f.duration))}function i(e,t,n){v=void 0!==t&&t,n=void 0!==n?n:"none",e=parseFloat(e);var i=u.length,r=e+1,a=e-1;r===i?r=0:a<0&&(a=i-1);for(var s=u.length-1;s>=0;s--)u[s].className="slide";i>1?(u[r].className="next slide","next"===n&&(u[r].className="next slide in-transition"),u[a].className="prev slide","prev"===n&&(u[a].className="prev slide in-transition"),u[e].className="current slide",g&&u[e].setAttribute("aria-live","polite"),c=e):u[0].className="current slide"}function r(){var e=u.length,t=c+1;t===e&&(t=0),g=!0,i(t,!1,"prev"),f.animate&&(p=setTimeout(r,f.duration))}function a(){var e=u.length,t=c-1;t<0&&(t=e-1),g=!0,i(t,!1,"next")}function s(){clearTimeout(p),f.animate=!1,h=!1;var e=document.getElementById("slideshowbutton");e.innerHTML=f.starttext,e.removeAttribute("data-stop"),e.setAttribute("data-start","true")}function o(){f.animate=!0,h=!1,p=setTimeout(function(){r()},5e3);var e=document.getElementById("slideshowbutton");e.innerHTML=f.stoptext,e.setAttribute("data-stop","true"),e.removeAttribute("data-start")}function l(){f.animate&&(clearTimeout(p),f.animate=!1,h=!0)}var d,u,c,m,f,p,v,h,g="false";return{init:n,next:r,prev:a,goto:i,stop:s,start:o}};if(document.getElementById("carousel")){var carousel=new myCarousel;carousel.init({id:"carousel",slidenav:!0,slidenavid:"slidenavid",animate:!0,startAnimated:!0,duration:6e3})}
/*

// * Rijkshuisstijl (Digitale Overheid) - details-element.js
// * ----------------------------------------------------------------------------------
// * Polyfill voor IE / Edge en knuppelbrowsers die details/summary tag niet kennen
// * ----------------------------------------------------------------------------------
// * @author  Paul van Buuren
// * @license GPL-2.0+
// * @package wp-rijkshuisstijl
// * @version 2.9.3
// * @desc.   JS + CSS voor inklapbare blokken.
// * @link    https://github.com/ICTU/digitale-overheid-wordpress-theme-rijkshuisstijl
 */
var alledetailstags=document.querySelectorAll("details"),currentElement,parent_of_element;if(alledetailstags.length>1){var liveregion_detailsummary="";function detailsbuttonListenFunc(e){var t=this.innerHTML,n=detailssummarytranslate.close;if(t==detailssummarytranslate.open){this.innerHTML=detailssummarytranslate.close,liveregion_detailsummary.textContent=detailssummarytranslate.detailsbutton_resultclose;for(var i=0;i<alledetailstags.length;i++)alledetailstags[i].setAttribute("open","")}else{n=detailssummarytranslate.open,liveregion_detailsummary.textContent=detailssummarytranslate.detailsbutton_resultopen;for(var i=0;i<alledetailstags.length;i++)alledetailstags[i].removeAttribute("open")}for(var r=document.querySelectorAll("button.openbutton"),i=0;i<r.length;i++)r[i].innerHTML=n}for(var i=0;i<alledetailstags.length;i++){parent_of_element=(currentElement=alledetailstags[i]).parentNode;var newNode=document.createElement("button");if(0==i){var myNewLiveRegion=document.createElement("div");myNewLiveRegion.setAttribute("role","region"),myNewLiveRegion.setAttribute("id","liveregion_detailsummary"),myNewLiveRegion.setAttribute("aria-live","polite"),myNewLiveRegion.innerHTML="Hier een paragraaf";var thelabel=detailssummarytranslate.detailsbutton_init.replace("__NUMBER__",alledetailstags.length);myNewLiveRegion.textContent=thelabel,parent_of_element.insertBefore(myNewLiveRegion,currentElement),liveregion_detailsummary=document.querySelector("#liveregion_detailsummary"),newNode.innerHTML=detailssummarytranslate.open,newNode.addEventListener("click",detailsbuttonListenFunc),newNode.classList.add("openbutton"),parent_of_element.insertBefore(newNode,currentElement)}i==alledetailstags.length-1&&(newNode.innerHTML=detailssummarytranslate.open,newNode.classList.add("openbutton"),newNode.addEventListener("click",detailsbuttonListenFunc),parent_of_element.insertBefore(newNode,currentElement.nextSibling))}}!function(){for(var e=document.querySelectorAll(".collapsetoggle"),t=0;t<e.length;t++){var n;e[t].querySelector("button").onclick=function(e){var t="true"===this.getAttribute("aria-expanded")||!1,n=this.parentElement.nextElementSibling;t?(this.setAttribute("aria-expanded",!1),n.setAttribute("hidden","hidden")):(this.setAttribute("aria-expanded",!0),n.removeAttribute("hidden"))}}}();
